### ISSUE TITLE
[Pin] Showcase

### ISSUE THREAD

**Issue by cworld1** [cworld1/astro-theme-pure#10]
This is for awesome things. If you want to join this list, please leave info on this issue.

这里是 Awesome astro-theme-pure 展示台。如果你也想加入这个展示台列表（部署案例 / 相关拓展文档），请不要吝啬在下方留言。

## Demos

- [Official Demo](https://astro-theme-pure.vercel.app/) | [Github](https://github.com/cworld1/astro-theme-pure)
- [CWorld Site](https://cworld0.com/) | [Github](https://github.com/cworld1/cworld1)
- [Arthals](https://arthals.ink/)
- [Xingluo's Blog](https://blog.en.icu/)
- [K1tyoo' ink](https://www.k1tyoo.ink/)
- [Ethan's Site](https://www.ethan2k04.icu/)
- [lyt0112.com](https://www.lyt0112.com/) | [Github](https://github.com/EmptyBlueBox/blog-latest-opensource)

### Deploy

- Deploy to Cloudflare Pages (#9)

### Statistics / analytics

Common:

- [Vercount](https://github.com/EvanNotFound/vercount): 类似于不蒜子，仅统计 PV/UV 信息
- [自建 Umami 数据统计及个性化展示](https://blog.starsharbor.com/posts/solitude-about_umami/)

Only for Vercel：

- [Vercel Speed Insights](https://vercel.com/docs/frameworks/astro#speed-insights): 网站性能指标，生成文件 `/_vercel/speed-insights/script.js · 12.2 KiB`，全 JS 文件占比 55%，建议酌情按需开启
- [Vercel WebAnalytics](https://vercel.com/docs/frameworks/astro#using-vercel's-features-with-astro): 免费，量略小，分析丰富，月重置

### AI

- [使用 Cloudflare Worker + Vercel 无成本实现 AI 摘要](https://blog.hesiy.cn/posts/qwen-summary)
- [TianliGPT](https://github.com/zhheo/Post-Abstract-AI)

### Others

- [添加 keystatic实现网页发布文章](https://blog.en.icu/blog/2024-10-25-astro-%E6%B7%BB%E5%8A%A0-keystatic%E5%AE%9E%E7%8E%B0%E7%BD%91%E9%A1%B5%E5%8F%91%E5%B8%83%E6%96%87%E7%AB%A0/)
- [添加说说页面](https://blog.en.icu/blog/2024-10-12-astro-tian-jia-talk)

**Comment by cworld1** [comment]
![2024-10-23 17-17-19](https://github.com/user-attachments/assets/f2891168-2e49-4b8a-95fa-8f4f58ea32f2)

**Comment by EmptyBlueBox** [comment]
Here's a deployment case and a GitHub repo~

https://www.lyt0112.com

https://github.com/EmptyBlueBox/blog-latest-opensource

**Comment by cworld1** [comment]
@EmptyBlueBox Fantastic! I can't help but want to add friend link with you~

**Comment by EmptyBlueBox** [comment]
> @EmptyBlueBox Fantastic! I can't help but want to add friend link with you~

Absolutely! I've added your link to my site!

**Comment by cworld1** [comment]
@prrao87 Thank you! I hope you enjoy this theme! It is still in the early stages of development, so there may be some minor issues, especially when upgrading to a new version (maybe it won't need to be upgraded?). Please make sure to check the [breaking changes](https://astro-pure.js.org/docs/advanced/update#breaking-changes) if needed. If you encounter any problems, don't hesitate to let me know.


And I've read your post, and found a very small problem when change `April 28, 2023` to any other format; you probably only need to go to `src/site.config.ts` and change:

```ts
export const theme: ThemeUserConfig = {
  locale: {
    lang: 'en-US',
    attrs: 'en_US',
    // Date locale
    dateLocale: 'en-CA', // format like xxxx-xx-xx
    dateOptions: {  // it is equal to config `Intl.DateTimeFormatOptions`
		year: 'numeric',
		month: '2-digit',
		day: '2-digit'
	}
  },
}
```

you can check [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat#using_options) for more.

**Comment by prrao87** [comment]
> [@prrao87](https://github.com/prrao87) Thank you! I hope you enjoy this theme! It is still in the early stages of development, so there may be some minor issues, especially when upgrading to a new version (maybe it won't need to be upgraded?). Please make sure to check the [breaking changes](https://astro-pure.js.org/docs/advanced/update#breaking-changes) if needed. If you encounter any problems, don't hesitate to let me know.

The theme is great and already feels so mature! Though I do get some minor errors when building the site due to the things you mentioned related to UnoCSS. I suppose I'll have to keep an eye on your upgrades and see what I can port over to my customized version.

> And I've read your post, and found a very small problem when change `April 28, 2023` to any other format; you probably only need to go to `src/site.config.ts` and change:

> you can check [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat#using_options) for more.

Did you notice this issue when you opened the post in your time zone? It reads fine to me, but I'll take a look at the code you shared and learn more. Thanks again!

**Comment by cworld1** [comment]
@chiffonng I cannot open it. It says "This domain is pending renewal or has expired. Please contact the domain provider with questions."

**Comment by chiffonng** [comment]
> Just deployed my page to [mychiffonn.com](http://mychiffonn.com/) with Cloudfare Page. I made several UI changes, internal refactoring, and icon performance, documented in [CHANGELOG.md](https://github.com/chiffonng/blog-astro/blob/main/CHANGELOG.md). If you're interested in some of the changes I made I could contribute PRs back to the theme next week.
> 
> I want to customize the page a lot more but right now I'm quite satisfied with what I have.

Hi can you let me know and also add the showcase? Thanks!

**Comment by joeytoday** [comment]
我也使用的你的主题部署了个人网站：https://www.joeytoday.com/
感谢你的主题～我做了一些修改。

**Comment by cworld1** [comment]
@joeytoday 太 cool 了！真的相当棒的改版👍

**Comment by David7ce** [comment]
My website [david7ce.github.io](https://david7ce.github.io) using GItHub Pages and comments with Waline JS. Thanks for beautiful web template @cworld1 ✨

**Comment by DanielZhangyc** [comment]
我很喜欢 Pure 的设计，我将它移植到了 Halo 2.x，制作了一个独立的 Halo 主题版本：
[DanielZhangyc/astro-pure-halo](https://github.com/DanielZhangyc/astro-pure-halo)

项目中我已经注明原始项目来源、对照提交和 Apache License 2.0 许可证信息。项目还在逐步完善中，作为一个独立维护的 Halo 移植版，而非对原项目的替代。

再次感谢你的开源工作！如果你认为合适，我也很希望这个项目能够被收录到 Showcase 中

以下是我的个人博客（应用了移植版本的pure）：[blog](https://www.xy0v0.top/)

**Comment by cworld1** [comment]
@DanielZhangyc 已添加！不好意思之前忙忘了，翻邮箱才想起来
