### ISSUE TITLE
大佬，什么时候怼个灯箱

### ISSUE THREAD

**Issue by king-zhangbn** [cworld1/astro-theme-pure#11]

**Comment by cworld1** [comment]
唔，确实有兴趣。搜了一下有相关项目 https://github.com/JulianCataldo/web-garden/tree/develop/app/Lightbox ，但是似乎接入进 Markdown 大概率是需要一些技巧。好问题，有时间会考虑

**Comment by king-zhangbn** [comment]
https://fuwari.vercel.app/posts/guide/可以看看这个

**Comment by cworld1** [comment]
由已知信息得到相关的活跃的库：

- [photoswipe](https://www.npmjs.com/package/photoswipe): 55.1 kB, Doc https://photoswipe.com/getting-started/
- [photoviewer](https://www.npmjs.com/package/photoviewer): 99.1 kB, Doc https://nzbin.github.io/photoviewer/, 功能较复杂
- [fslightbox](https://www.npmjs.com/package/fslightbox): 30.1 kB, Doc https://fslightbox.com/javascript, 支持视频
- [baguettebox.js](https://www.npmjs.com/package/baguettebox.js): 9.69 kB, Doc https://feimosi.github.io/baguetteBox.js/
- [glightbox](https://www.npmjs.com/package/glightbox): 56.3 kB
- [@midzer/tobii](https://www.npmjs.com/package/@midzer/tobii): 23.2 kB, 支持视频
- [bigger-picture](https://www.npmjs.com/package/bigger-picture): 20.5 kB, 动画精美，支持视频

先就这样。明天细看。

**Comment by cworld1** [comment]
已在 #21 合并；已发布在 v3.1.3 版本中。
