### ISSUE TITLE
Typography has a image margin problem

### ISSUE THREAD

**Issue by king-zhangbn** [cworld1/astro-theme-pure#23]
look!
![CleanShot 2024-12-01 at 21 41 55@2x](https://github.com/user-attachments/assets/4ae14ede-5480-45ec-9037-27b720ab3ca1)
我感觉还是需要些空隙显得美观

**Comment by cworld1** [comment]
呃，没看懂。能否提供在线实例？或者最小 stackblitz 代码也行

**Comment by king-zhangbn** [comment]
就是图片与图片之间的上下联系要有空隙才美观，左边是新版，右边的是老版本，

**Comment by cworld1** [comment]
与 lightbox 无关，大概率是最近折腾 Typography 导致。预计将在 v3.1.4 版本修复。感谢指出。

**Comment by king-zhangbn** [comment]
好耶！感谢
