### ISSUE TITLE
浅色模式下代码显示不对，深色模式正常反色

### ISSUE THREAD

**Issue by king-zhangbn** [cworld1/astro-theme-pure#24]
![CleanShot 2024-12-01 at 23 34 16@2x](https://github.com/user-attachments/assets/b5aa269b-a772-4978-a720-46b84e4ab762)
---
![CleanShot 2024-12-01 at 23 43 54@2x](https://github.com/user-attachments/assets/c8e834f0-f5e2-447d-8780-c7c3e8a37b21)

**Comment by cworld1** [comment]
你测试一下，是不是只有未被 https://shiki.matsu.io/languages.html 支持的语言才有这个问题？有的话属于默认主题违背覆盖问题。下个版本修复。

**Comment by cworld1** [comment]
你有方便的聊天平台吗？如果有兴趣可以添加到组。（当然如果用TG就更好了）

**Comment by king-zhangbn** [comment]
我尝试修改成指定语言，已经解决啦。

**Comment by king-zhangbn** [comment]
当然！我有TG，tg：@xingluo2024
