### ISSUE TITLE
OMG，我遇到了点问题，关于这个字段remarkPluginFrontmatter

### ISSUE THREAD

**Issue by king-zhangbn** [cworld1/astro-theme-pure#25]
我今天闲的慌想更新一下到最新版本，因为换仓库了，我大部分重新折腾了一下，但是遇到了remarkPluginFrontmatter这个字段的问题，
![image](https://github.com/user-attachments/assets/ec8f82bf-23bd-4e44-af8f-479c7a0f54ab)

src/components/blog/Hero.astro:16:9 - error ts(2339): Property 'remarkPluginFrontmatter' does not exist on type 'RenderResult | { Content(props: Record<string, any>): AstroComponentFactory; headings: MarkdownHeading[]; }'.

但是我将hero.ASTRO中的

```
const { remarkPluginFrontmatter } = await render()
```

变成

```
const { remarkPluginFrontmatter } = (await render()) as {
  remarkPluginFrontmatter: Record<string, any>;
};
```

好像就可以跑了

**Comment by cworld1** [comment]
@king-zhangbn 这个代码好像是预估阅读时间的，我这上次提交的时候貌似没有这个问题。是类似于“提交了一个空白文档”之类的特殊情况吗

**Comment by king-zhangbn** [comment]
不是，我的所有文档都是有内容的诶，我也不知道这是什么情况诶，但是现在能跑！啊哈

**Comment by cworld1** [comment]
@king-zhangbn 因为这个项目使用typescript，所以any类型会被linter警告为 unexpected type。看来得把类型敲定。等待后续更新。

**Comment by cworld1** [comment]
下次更新改动较大，故现有设定无法作用。不排除这里可能会出现问题。如有问题还请继续反馈。
