### ISSUE TITLE
下次可以安排上表格视图，md的表格无法识别

### ISSUE THREAD

**Issue by king-zhangbn** [cworld1/astro-theme-pure#30]
![image](https://github.com/user-attachments/assets/cef17c8a-bfc4-4d46-8d72-fe767bf58ee2)

**Comment by cworld1** [comment]
markdown 原生表格视图是支持的：

https://cworld0.com/blog/national-language

对应写法：

https://vscode.dev/github/cworld1/cworld1/blob/main/src/content/post/national-language.md#L12

**Comment by king-zhangbn** [comment]
我知道了，是keystatic的写法有问题

**Comment by cworld1** [comment]
嗯。？没懂到。你能解决问题就行
