### ISSUE TITLE
这favicon肯定写错了！

### ISSUE THREAD

**Issue by king-zhangbn** [cworld1/astro-theme-pure#31]
![image](https://github.com/user-attachments/assets/d50001e6-1145-4c20-9ea0-0c0bfa8787f3)

**Comment by cworld1** [comment]
确实，后面可以改一下

注：

1. 仅用作示例，实际头像可不能用这么模糊的图像
2. 更应该是写avatar.png那个，看能不能链接进去
3. 但其实更推荐 gravatar.com 等专业服务地址
4. 推荐配置参考：https://vscode.dev/github/cworld1/cworld1/blob/main/src/site.config.ts#L162
