### ISSUE TITLE
一些小建议？

### ISSUE THREAD

**Issue by king-zhangbn** [cworld1/astro-theme-pure#32]
我目前将`{ Aside }`该插件集成到keystatic里面了，
![image](https://github.com/user-attachments/assets/122b4e72-1dfd-4064-ba9a-42d9b5f3b7eb)
![image](https://github.com/user-attachments/assets/389f778a-8051-4054-a7fc-1ed984396408)

但是有个问题，就是我需要每次给文章里面添加啊`import { Aside } from '@/components/user'`这段话，这个可以集成到大框架里面吗？就是不需要我每次输入`import { Aside } from '@/components/user'`，只要输入
`<Aside type='caution' title='You should know it!'>Is your code buggy again? 🤨</Aside>`
就可以直接应用aside的样式

**Comment by cworld1** [comment]
有，下次写文档里面

https://github.com/delucis/astro-auto-import/tree/main/packages/astro-auto-import

**Comment by king-zhangbn** [comment]
ok！解决了
